use_default_settings:
  engines:
    keep_only: [startpage, yahoo, mojeek, qwant]
engines:
  - name: startpage
    disabled: false
  - name: yahoo
    disabled: false
  - name: mojeek
    disabled: false
  - name: qwant
    disabled: false
general:
  instance_name: Forge Search
search:
  safe_search: 1
  formats: [html, json]
server:
  bind_address: 0.0.0.0
  port: 8080
  limiter: false
  image_proxy: false
outgoing:
  request_timeout: 8.0
  max_request_timeout: 12.0